### ISSUE TITLE
Unable to parse the rule "SIGN ::= [+-]"

### ISSUE THREAD

**Issue by vsajip** [Chrriis/RRDiagram#24]
The above rule causes an exception:
```console
Caused by: java.lang.IndexOutOfBoundsException: Index -1 out of bounds for length 1
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:248)
	at java.base/java.util.Objects.checkIndex(Objects.java:374)
	at java.base/java.util.ArrayList.get(ArrayList.java:459)
	at net.nextencia.rrdiagram.grammar.model.BNFToGrammar$Chunk.prune(BNFToGrammar.java:116)
	at net.nextencia.rrdiagram.grammar.model.BNFToGrammar$Chunk.prune(BNFToGrammar.java:148)
	at net.nextencia.rrdiagram.grammar.model.BNFToGrammar$Chunk.access$100(BNFToGrammar.java:35)
	at net.nextencia.rrdiagram.grammar.model.BNFToGrammar.createRule(BNFToGrammar.java:344)
	at net.nextencia.rrdiagram.grammar.model.BNFToGrammar.convert(BNFToGrammar.java:313)
```
whereas `SIGN ::= [xy]` is successfully parsed. Are you supposed to use some special escaping?

**Comment by Chrriis** [comment]
Perhaps I misunderstand the issue, but I think this rule is invalid BNF. It reads:
The rule SIGN is the optional element called "+-".
The problem is that "+-" is an invalid rule name.

I think what you meant for your rule is: the rule SIGN is either the character "+" or the character "-".
This translates to:
SIGN ::= "+" | "-";

**Comment by vsajip** [comment]
Ah - OK, I see. It's just an issue of the dialect of EBNF, perhaps - the `bottlecaps.de` railroad diagram generator of Gunther Rademacher (whose site you cite as an inspiration) handles it just fine, though it escapes the `-` in the character set on output.

![ss41](https://github.com/Chrriis/RRDiagram/assets/130553/0f7a192b-3a1a-44d1-9dd2-aba5d2485ead)
